version: '2.1'

services:

  elasticsearch:
    image: elasticsearch:$VERSION_ELASTICSEARCH
    container_name: elasticsearch
    #build: "https://git.scimetis.net/yohan/docker-elasticsearch.git"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    expose:
      - '9200'
      - '9300'
    networks:
      - reverse-proxy
    volumes:
      - /mnt/volumes/elasticsearch_data/data:/usr/share/elasticsearch/data

networks:
  reverse-proxy:
    external: true
